Filter cgroup2 process to support tracing container
iovisor/bcc pull request #3741
Opened 2021-12-08 07:04 UTC by chethanah

- There are many libbpf-tools with various options. But we cannot pass cgroups path for filtering processes in cgroup.
- Example: https://github.com/iovisor/bcc/blob/master/libbpf-tools/tcpconnect.c#L177, cgroup is not yet implemented

### How to trace only cgroup2 processes? Consider the following flow:
- On user side:
  - Pass cgroup path to user code, 
  - Get the fd of cgroup path
  - Update the fd to a map of type BPF_MAP_TYPE_CGROUP_ARRAY. This will store the fd of cgroup path.
- On BPF side 
  - Using bpf_current_task_under_cgroup, 
    - check if current task is not under cgroup fd, then exit
    - If current task is under cgroup fd, then continue BPF code

### Example Usage: biosnoop
- Build biosnoop 
```
$ cd libbpf-tools/
$ make biolatency biosnoop 
```
- Run biosnoop (**Cgroup default-hierarchy=hybrid**)
```
// Terminal 1 
# mkdir /sys/fs/cgroup/unified/test 
# echo $$ > /sys/fs/cgroup/unified/test/cgroup.procs 
# cat /proc/$$/cgroup 
12:freezer:/
11:cpuset:/
10:net_cls,net_prio:/
9:blkio:/user.slice
8:devices:/user.slice
7:perf_event:/
6:rdma:/
5:pids:/user.slice/user-1000.slice/user@1000.service
4:hugetlb:/
3:memory:/user.slice/user-1000.slice/user@1000.service
2:cpu,cpuacct:/user.slice
1:name=systemd:/user.slice/user-1000.slice/user@1000.service/vte-spawn-f9f3e7b6-62bc-4d29-ab24-79464167eb61.scope
0::/test

// Start tracer in Terminal 2
# cat /dev/random > /log 
^C

// Terminal 2 
$ sudo ./biosnoop -c /sys/fs/cgroup/unified/test/
TIME(s)     COMM           PID    DISK    T    SECTOR     BYTES   LAT(ms)
0.000000    cat            116681 nvme0n1 W    42735584   16384     0.025
0.000349    cat            116681 nvme0n1 W    42735616   1040384   0.368
0.000720    cat            116681 nvme0n1 W    42737648   1040384   0.733
0.000728    cat            116681 nvme0n1 W    42739680   16384     0.485
0.001108    cat            116681 nvme0n1 W    42739712   1040384   0.860
0.001497    cat            116681 nvme0n1 W    42741744   1040384   1.242
...<SKIP>...
```

### Example usage with OCI containers
- These options can additionally be used for tracing containers 
- We can get the container cgroup2 path and add path fd to map (Example: OCI runc creates cgroup under `/sys/fs/cgroup/unified/`)
```
// Terminal 1 - launch container with spec cgroupsPath=/runc
# runc run test 
root@runc:/# strace -f -o ./log ping -c 1 localhost 
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.031 ms

--- localhost ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.031/0.031/0.031/0.000 ms
root@runc:/#

// Terminal 2 
$ sudo ./biosnoop -c /sys/fs/cgroup/unified/runc
TIME(s)     COMM           PID    DISK    T    SECTOR     BYTES   LAT(ms)
0.000000    strace         107385 nvme0n1 RA   906454648  262144    0.245
0.000076    strace         107385 nvme0n1 RA   906456784  77824     0.162
0.000676    strace         107385 nvme0n1 RA   906455160  262144    0.278
0.027123    strace         107385 nvme0n1 W    29156792   20480     0.025
^C
```
- Can also be used with OCI hooks. This will enable us to trace from start of container process.
- Further can be used with K8s-CRIO prestart/postart hooks.

## Conclusion
- Update cgroup2 fd in map and using bpf_current_task_under_cgroup() we can filter only processes under respective cgroup.
  - This will help us trace containers and integrate it with OCI hooks.
- Currently these changes are implemented only for biosnoop and biolatency as example, need community's feedback and suggestions to improve for other tools.

2021-12-08 15:37 UTC, chenhengqi requested changes

2021-12-08 15:37 UTC, chenhengqi commented on libbpf-tools/biolatency.bpf.c
> +bool cgroup = false;
`const volatile`

2021-12-08 15:37 UTC, chenhengqi commented on libbpf-tools/biolatency.bpf.c
> +	__uint(value_size, sizeof(u32));
This can be written as:
```c
__type(key, u32);
__type(value, u32);
```

2021-12-08 15:37 UTC, chenhengqi commented on libbpf-tools/biolatency.bpf.c
> +	}
combine these two conditions with `&&` ?

2021-12-08 15:37 UTC, chenhengqi commented on libbpf-tools/biolatency.bpf.c
> +	}
Please also follow the kernel code style. Add a space after `if` and drop the brackets.

2021-12-08 15:37 UTC, chenhengqi commented on libbpf-tools/biolatency.bpf.c
> +	if(cgroup)
ditto

2021-12-08 15:37 UTC, chenhengqi commented on libbpf-tools/biolatency.c
> +	// update cgroupsPath fd to map
No C++ style comment.

2021-12-08 15:37 UTC, chenhengqi commented on libbpf-tools/biolatency.c
> +		if (cgfd < 0) {
Declare these variables first ?

2021-12-08 15:37 UTC, chenhengqi commented on libbpf-tools/biosnoop.bpf.c
> +bool cgroup = false;
Please update this tool accordingly.

2021-12-09 05:40 UTC, chethanah commented
Thank you @chenhengqi for your feedback. 
I've updated changes based on review points. Kindly verify.

2021-12-09 06:02 UTC, chenhengqi commented on libbpf-tools/biolatency.c
> +	{
`if (env.cg) {`

2021-12-09 06:02 UTC, chenhengqi commented on libbpf-tools/biolatency.c
> +		cgfd = open(env.cgroupspath, O_RDONLY);
`close(cgfd)` on cleanup.

2021-12-09 13:53 UTC, chethanah commented on libbpf-tools/biolatency.c
> +		cgfd = open(env.cgroupspath, O_RDONLY);
Ah! sorry I missed to close fd

2021-12-09 13:53 UTC, chethanah commented
Pushed changes based on review comments

2021-12-09 15:41 UTC, chenhengqi commented on libbpf-tools/biolatency.c
> +	int idx, cg_map_fd, cgfd;
`cgfd` should be initialized to some invalid value like `-1`.

2021-12-09 15:41 UTC, chenhengqi commented on libbpf-tools/biolatency.c
> +	close(cgfd);
Cleanup in reverse order so that BPF program won't reference invalid fd.
Do close only when cgfd > 0.

2021-12-09 15:41 UTC, chenhengqi commented on libbpf-tools/biosnoop.c
> +	int idx, cg_map_fd, cgfd;
Same here.

2021-12-10 05:22 UTC, chenhengqi approved these changes
LGTM

2021-12-11 18:56 UTC, merged

2023-06-01 02:46 UTC, chethanah commented
> I am not sure if my question is related to this issue. But is there an efficient way to filter to trace pids associated with programs running in a container?

@Anjali05 , have you tried `execsnoop` tool 
I'm not sure, if this can be discussed in MR.
Lists the pids and commands exec'd. **But not already running pids**

- Launch container
```
$ docker run -it --rm bash 
bash-5.2# 
```
- get container cgroup path (cgroup filtering supported only for cgroup2)
```
$ ps aux | grep bash 
root       70891  1.0  0.0   2748  2268 pts/0    Ss+  08:04   0:00 bash

$ cat /proc/70891/cgroup 
0::/system.slice/docker-4bff7ef24e402ec8f057562710a78fbf6ad05816ddc492226a5d90ab533d5728.scope
```
- launch `execsnoop`
```
$ sudo ./execsnoop -c /sys/fs/cgroup/system.slice/docker-4bff7ef24e402ec8f057562710a78fbf6ad05816ddc492226a5d90ab533d5728.scope/ 
PCOMM            PID    PPID   RET ARGS
ls               72635  70891    0 /bin/ls 
sleep            72704  70891    0 /bin/sleep 1 
```
- But `cgroup.procs` simply gives all the pids running in that cgroup path
```
$ cat /sys/fs/cgroup/system.slice/docker-4bff7ef24e402ec8f057562710a78fbf6ad05816ddc492226a5d90ab533d5728.scope/cgroup.procs 
70891
```

2023-06-04 02:42 UTC, chenhengqi commented
@Anjali05  See bpf_get_ns_current_pid_tgid() helper.

2023-06-05 15:25 UTC, Anjali05 commented
@chenhengqi I understand we can use bpf_get_ns_current_pid_tgid()  to filter pids while using bcc for tracing. The use case I am looking at is a bit different from all the examples I have looked at. I do not know the pid of the process before starting the trace. The use case is I start the tracing program, the container is already running but I start executing the workload inside the container after the trace program starts. So I do not know the pid of the workload beforehand. I was thinking of any way in which I can filter just the workload running inside the container. Also my trace program runs on the host machine and not inside the container.

2023-06-05 15:39 UTC, Anjali05 commented
> > I am not sure if my question is related to this issue. But is there an efficient way to filter to trace pids associated with programs running in a container?
> 
> @Anjali05 , have you tried `execsnoop` tool I'm not sure, if this can be discussed in MR. Lists the pids and commands exec'd. **But not already running pids**
> 
>     * Launch container
> 
> 
> ```
> $ docker run -it --rm bash 
> bash-5.2# 
> ```
> 
>     * get container cgroup path (cgroup filtering supported only for cgroup2)
> 
> 
> ```
> $ ps aux | grep bash 
> root       70891  1.0  0.0   2748  2268 pts/0    Ss+  08:04   0:00 bash
> 
> $ cat /proc/70891/cgroup 
> 0::/system.slice/docker-4bff7ef24e402ec8f057562710a78fbf6ad05816ddc492226a5d90ab533d5728.scope
> ```
> 
>     * launch `execsnoop`
> 
> 
> ```
> $ sudo ./execsnoop -c /sys/fs/cgroup/system.slice/docker-4bff7ef24e402ec8f057562710a78fbf6ad05816ddc492226a5d90ab533d5728.scope/ 
> PCOMM            PID    PPID   RET ARGS
> ls               72635  70891    0 /bin/ls 
> sleep            72704  70891    0 /bin/sleep 1 
> ```
> 
>     * But `cgroup.procs` simply gives all the pids running in that cgroup path
> 
> 
> ```
> $ cat /sys/fs/cgroup/system.slice/docker-4bff7ef24e402ec8f057562710a78fbf6ad05816ddc492226a5d90ab533d5728.scope/cgroup.procs 
> 70891
> ```

I will try it.

2023-06-05 15:45 UTC, Anjali05 commented
> @Anjali05 See bpf_get_ns_current_pid_tgid() helper.

I will look into it.