Show the stacktrace of the userspace in opensnoop.
iovisor/bcc pull request #4186
Opened 2022-08-17 16:42 UTC by ThinkerYzu1

With new option '-c', opensnoop will show the names and line numbers
of the two most inner callers in the userspace if there are.  It
uses BlazeSym to do symbolization.

Signed-off-by: Kui-Feng Lee <kuifeng@fb.com>

2022-08-17 16:47 UTC, ThinkerYzu1 commented
The output of `opensnoop -c`  looks like
```
2669466 python3.8         -1   2 /etc/userdb
                                 files_add
                                 conf_files_list_strv_internal
2669466 python3.8         -1   2 /run/userdb
                                 files_add
                                 conf_files_list_strv_internal
2669466 python3.8         -1   2 /run/host/userdb
                                 files_add
                                 conf_files_list_strv_internal
```

It shows the two most inner callers of the syscall if there are.

2022-08-20 17:16 UTC, davemarchevsky commented
Probably the best way to solve the "dubious ownership" issue will be to modify `CMakeLists.txt` similar to what `libbpf` and `bpftool` do here: https://github.com/iovisor/bcc/blob/master/CMakeLists.txt#L34 . A little confusing perhaps since `libbpf-tools` dir is not using the `cmake` build system like rest of `bcc` repo.

Speaking of makefiles, it would be good to gate the `blazesym` build behind some flag and have that propagated to the `opensnoop.c` userspace runner, so that `-c` flag and added functionality aren't available if `blazesym` isn't built. Totally fine to have the `USE_BLAZESYM` or whatever on by default, but want to give folks an out if they don't want to have `rustc`/`cargo` dependency.  In long run if we migrate to blazesym by default we can just remove it.

2022-08-22 19:59 UTC, ThinkerYzu1 commented
The error now is caused by the absence of cargo.  How can I make cargo/rustc available?

2022-08-24 16:33 UTC, davemarchevsky requested changes

2022-08-24 16:33 UTC, davemarchevsky commented on CMakeLists.txt
> +    execute_process(COMMAND git config --global --add safe.directory ${CMAKE_CURRENT_SOURCE_DIR}
This `execute_process` statement and 

> Failed to add root source directory to safe.directory"

warning check should happen for both blazesym and libbpf submodule usage. I think it's fine for it to live outside of both `if(NOT NO_BLAZESYM)` and `if(NOT CMAKE_USE_LIBBPF_PACKAGE)` checks.

2022-08-24 16:33 UTC, davemarchevsky commented on CMakeLists.txt
> +      message(WARNING "Failed to update submodule libbpf")
can you update the warning text here?

2022-08-24 17:18 UTC, davemarchevsky commented
re: rust and cargo, can you add this change to `docker/build/Dockerfile.fedora`:

```
+++ b/docker/build/Dockerfile.fedora
@@ -41,6 +41,10 @@ RUN dnf -y install \
        python3 \
        python3-pip

+RUN dnf -y install \
+       rust \
+       cargo
+
 RUN if [[ ! -e /usr/bin/python && -e /usr/bin/python3 ]]; then \
```

2022-09-06 20:38 UTC, merged